### ISSUE TITLE
A small inaccuracy in the sample configuration file: less-watch-compiler.config.json

### ISSUE THREAD

**Issue by alessandromaggioniweb** [jonycheung/deadsimple-less-watch-compiler#102]
Version: 1.14.6

I report only a small inaccuracy in the sample configuration file:

<div class="highlight highlight-source-json"><pre>{
    <span class="pl-s"><span class="pl-pds">"</span>watchFolder<span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>&lt;input_folder&gt;<span class="pl-pds">"</span></span>,   
    <span class="pl-s"><span class="pl-pds">"</span>outputFolder<span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>&lt;output_folder&gt;<span class="pl-pds">"</span></span>,
    <span class="pl-s"><span class="pl-pds">"</span>mainFile<span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>&lt;main-file&gt;<span class="pl-pds">"</span></span>,   
    <span class="pl-s"><span class="pl-pds">"</span>sourceMap<span class="pl-pds">"</span></span>: <span class="pl-c1">false</span>,
    <span class="pl-s"><span class="pl-pds">"</span>plugins<span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>plugin1,plugin2<span class="pl-pds">"</span></span>,
    <span class="pl-s"><span class="pl-pds">"</span><b>less-args</b><span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>option1=1,option2=2<span class="pl-pds">"</span></span>,
    <span class="pl-s"><span class="pl-pds">"</span>runOnce<span class="pl-pds">"</span></span>: <span class="pl-c1">false</span>,
    <span class="pl-s"><span class="pl-pds">"</span>enableJs<span class="pl-pds">"</span></span>: <span class="pl-c1">true</span>
}</pre></div>

Should be:

<div class="highlight highlight-source-json"><pre>{
    <span class="pl-s"><span class="pl-pds">"</span>watchFolder<span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>&lt;input_folder&gt;<span class="pl-pds">"</span></span>,   
    <span class="pl-s"><span class="pl-pds">"</span>outputFolder<span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>&lt;output_folder&gt;<span class="pl-pds">"</span></span>,
    <span class="pl-s"><span class="pl-pds">"</span>mainFile<span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>&lt;main-file&gt;<span class="pl-pds">"</span></span>,   
    <span class="pl-s"><span class="pl-pds">"</span>sourceMap<span class="pl-pds">"</span></span>: <span class="pl-c1">false</span>,
    <span class="pl-s"><span class="pl-pds">"</span>plugins<span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>plugin1,plugin2<span class="pl-pds">"</span></span>,
    <span class="pl-s"><span class="pl-pds">"</span><b>lessArgs</b><span class="pl-pds">"</span></span>: <span class="pl-s"><span class="pl-pds">"</span>option1=1,option2=2<span class="pl-pds">"</span></span>,
    <span class="pl-s"><span class="pl-pds">"</span>runOnce<span class="pl-pds">"</span></span>: <span class="pl-c1">false</span>,
    <span class="pl-s"><span class="pl-pds">"</span>enableJs<span class="pl-pds">"</span></span>: <span class="pl-c1">true</span>
}</pre></div>

Have a nice day 👍

**Comment by jonycheung** [comment]
Thanks! I fixed it just now.
