### ISSUE TITLE
Output unminified CSS and keep file description

### ISSUE THREAD

**Issue by Nihilivin** [jonycheung/deadsimple-less-watch-compiler#11]
Hello,
Thank you for this small script, it will be useful to speed up my project.

I'd like to output unminified stylesheets, as I already have a minifying process otherwhere. Also, I'm used to start all my files with something like
`/**
 * @file iThoughts Tooltip Glossary tinymce form styles
 * @author Gerkin
 * @licence LGPLv2
 *         
 * @version 1.0
 */`

and the compiling process strip out this comment... Is it possible to keep it?

Thank you for your help

**Comment by jonycheung** [comment]
@Nihilivin I've added the ability to set a "minified" flag in the json to disable minifying files. Take a look.

**Comment by Nihilivin** [comment]
Fine, seems perfect
