### ISSUE TITLE
Feature: --run-initially flag to compile once and then watch

### ISSUE THREAD

**Issue by uosl** [jonycheung/deadsimple-less-watch-compiler#115]
When our project is freshly cloned, it will be missing the CSS file and less-watch-compiler won't build it until there's a change in the less sources. This leads to having to run it twice: `npx less-watch-compiler --run-once less/ resources/public/css/ site.less && npx less-watch-compiler less/ resources/public/css/ site.less`.

It seems it would be useful to have a `--run-initially` flag which makes it compile once (similarly to `--run-once`) but it stays running in watch mode, to recompile on changes.

Edit: As an example, [chokidar-cli](https://github.com/kimmobrunfeldt/chokidar-cli) provides this flag: `  --initial               When set, command is initially run once`

**Comment by jonycheung** [comment]
@uosl less-watch-compiler should do an initial compile when run without the `--run-once` flag. Is that not sufficient? I double check that this works. Are you sure you don't have a race condition on your end?

**Comment by uosl** [comment]
Sorry for the very late response!

You're right - I made a minimal reproduction and it does do an initial compile. I'm not sure what's up with our project setup to cause what I described, but it doesn't seem to be related to the tool.
