### ISSUE TITLE
Command line/Json options

### ISSUE THREAD

**Issue by guanzo** [jonycheung/deadsimple-less-watch-compiler#13]
Can we specify an output file instead of folder? Instead of each .less file compiling into a .css file, i want all .less files to compile into a single .css file. Also, is there an option for the third parameter in the json file?

**Comment by daniloster** [comment]
The new version already has it... You need to define the main input file which imports the other ones. So, if your file is main.less, it will be generated a main.css.

The name of the file must be specified as 3rd parameter.

**Comment by andycastles** [comment]
In the config.json file the third parameter is called `mainFile` in the `defaults` section.

**Comment by jonycheung** [comment]
thanks!
