### ISSUE TITLE
--run-once parameter is not working anymore

### ISSUE THREAD

**Issue by PH89** [jonycheung/deadsimple-less-watch-compiler#137]
**Which version are you using (less-watch-compiler --version to find out)?**
1.15.1

**Is the issue reproducible after updating to the latest version ( npm update less-watch-compiler)?**
Yes

**Describe the bug**
--run-once is ignored and the less-watch-compiler is watching for file changes.

**To Reproduce**
Simple use --run-once on a version higher then 1.14.7

**Desktop (please complete the following information):**
 - OS: Mac OSX 11.3.1

**Comment by jonycheung** [comment]
I'm working on this. Should have a fix soon.

**Comment by jonycheung** [comment]
v1.15.2 should have a fix for this. Please
