### ISSUE TITLE
files that @import a changed file are not updated

### ISSUE THREAD

**Issue by Pomax** [jonycheung/deadsimple-less-watch-compiler#15]
If I have a directory with two files, `a.less` and `b.less`, where `a.less` has an `@import "b.less";` instruction, running this watcher on the less directory will not lead to `a.less` being recompiled when `b.less` is saved, essentially voiding the very reason to use it.

The third-arg-for-main-entry-point works if you have a less dir with a single "master" file, but only pushes the problem a bit further out: if there are two or more master files (for instance, you have a project with multiple themes that all rely on the same `colors.less` or something) then you still run into this problem where only one theme will get recompiled and the rest just sit there doing nothing.

A list of "master files" that all get recompiled when a save happens, rather than just a single file, would be quite useful, although a file parse to find the import hierarchy would of course be the best solution.

**Comment by Ciantic** [comment]
I need this dependency tree feature also, it's main thing keeping me using ancient https://github.com/gdupont/less-monitor - it knows the dependency graph and builds all files smartly.

**Comment by jonycheung** [comment]
Great input. I had the same thought but haven't had time to add this feature. It's on my list.

**Comment by jonycheung** [comment]
This should be fixed in the latest release.
