### ISSUE TITLE
Unable to pass plugins to the lessc

### ISSUE THREAD

**Issue by Ciantic** [jonycheung/deadsimple-less-watch-compiler#18]
I need to pass plugins to lessc command. E.g. `lessc --glob` the extra parameter there is [less glob plugin](https://github.com/just-boris/less-plugin-glob).

**Comment by jonycheung** [comment]
@Ciantic I think I'd just add the ability to add plugins in the config.json file. What do you think?

**Comment by ciwchris** [comment]
@jonycheung sounds great to me. I'm looking at using [less-plugin-csscomb](https://github.com/bassjobsen/less-plugin-csscomb) and so would need to add `--csscomb`.

**Comment by ctolkien** [comment]
+1 to this, we cannot seem to pass a `--source-map` option to generate source maps?

**Comment by Ciantic** [comment]
Btw, I have since then started to use "watch-run" tool, which works for me since all less files are compiled to one css file in my projects:

`watch-run -p "**/*.less" "lessc --verbose --source-map --glob style.less style.css"`

**Comment by ctolkien** [comment]
Yep, we've migrated to watch-run too.

**Comment by jonycheung** [comment]
Sorry for the late reply. I've introduced `--source-map` support. plugins is next

**Comment by jonycheung** [comment]
This is now possible. Let me know if you have any issues.
