### ISSUE TITLE
Error on multiple PC's

### ISSUE THREAD

**Issue by VasilNikolov** [jonycheung/deadsimple-less-watch-compiler#20]
Watching directory for file changes.

C:\Users\Vasil\AppData\Roaming\npm\node_modules\less-watch-compiler\lib\lessWatchCompilerUtils.js:72
                if (err) throw err;
                         ^

Error: ENOENT: no such file or directory, stat 'C:\Projects\Less course\First\styles\less\styles\less'
    at Error (native)

ON MULTIPLE PC's

**Comment by jonycheung** [comment]
@VasilNikolov  in your case, does `'C:\Projects\Less course\First\styles\less\styles\less'` exist?

**Comment by VasilNikolov** [comment]
@jonycheung Yes it does exist but i think the problem is on the mentioned file and line.

**Comment by jonycheung** [comment]
@VasilNikolov Could you try the latest and let me know if this is still an issue. If so, please re-open.
