### ISSUE TITLE
& .class should allow space between the "&" and the ".".  Currently it puts the space into the css file which will cause it not work.

### ISSUE THREAD

**Issue by caltonji** [jonycheung/deadsimple-less-watch-compiler#22]
Defects:
- [x] Did you run `npm install` and `npm update`
- [x] Did you pull the latest code from `master` branch?

Steps to reproduce:
#
#
#

Actual Results:
-

Expected Results:
-

**Comment by jonycheung** [comment]
@caltonji I checked and it works. do you have some sample less code you can share?
