### ISSUE TITLE
Folder structure of output folder doesn't fit to the source folder

### ISSUE THREAD

**Issue by sergeykifyak** [jonycheung/deadsimple-less-watch-compiler#26]
Defects:
- [x] Did you run `npm install` and `npm update`
- [x] Did you pull the latest code from `master` branch?

Steps to reproduce:

- Create folder structure like this:
```
styles
|-- components
|---- buttons.less
|-- app.less
|-- index.less
```
- Compile/watch the less by `less-watch-compiler styles styles`

Actual Results:
```
styles
|-- components
|---- buttons.less
|-- app.less
|-- app.css
|-- buttons.css
|-- index.less
|-- index.css
```

Expected Results:
```
styles
|-- components
|---- buttons.less
|---- buttons.css
|-- app.less
|-- app.css
|-- index.less
|-- index.css
```

**Comment by jonycheung** [comment]
Thanks. There are some assumptions that the utility makes. It assumes that it renders into the root directory. And that sub-directories would contain only included files. 

I need to rewrite some of the code that I borrowed from another library inside lessWatchCompilerUtils.js. If you are interested, let me know.

**Comment by eugene-matvejev** [comment]
confirmed, I think it is important thing :)

**Comment by kusmierz** [comment]
Any chance to fix this?

**Comment by jonycheung** [comment]
Sorry. I haven't had time recently. Marking this as help wanted
