### ISSUE TITLE
Filesearch.js Syntax error

### ISSUE THREAD

**Issue by brandon-morgan** [jonycheung/deadsimple-less-watch-compiler#31]
Defects:
- [x] Did you run `npm install` and `npm update`
- [ ] Did you pull the latest code from `master` branch?

Steps to reproduce:
# Ran command to compile less according to readme
#
#

Actual Results:
- Syntax error `Unexpected Token [` Line 15 of filesearch.js `let [ , filename ] = m;`

Expected Results:
- A colleague of mine uses this repo and works for him, however after looking into file structure  it was noticed that he doesn't even have a filesearch.js in lib directory, so must have been an update since he installed which is causing the error.

**Comment by codedebug** [comment]
I also get the same error after fresh $ npm install -g less-watch-compiler

Line 15 of filesearch.js
`let [ , filename ] = m;`

Syntax error: `Unexpected Token [`

**Comment by codedebug** [comment]
/lib/filesearch.js commit version 1.5.1 is working, after this the code has the syntax error highlighted above

**Comment by jonycheung** [comment]
@codedebug  Thanks. which version of node and npm do you have installed?

**Comment by codedebug** [comment]
Using Node v4.4.7 and NPM v2.15.8 at the moment

**Comment by jonycheung** [comment]
@codedebug Ah, the latest would work only with node v6+ since I'm using some ES2015 in it? Is it possible to upgrade or use `nvm`?

**Comment by jonycheung** [comment]
I'll spend some time to setup babel to make this node4 compatible. In the meantime, you could upgrade to node v6 and get this working immediately.

**Comment by jonycheung** [comment]
1.6.15 fixes this issue
