### ISSUE TITLE
missing option: included paths

### ISSUE THREAD

**Issue by eugene-matvejev** [jonycheung/deadsimple-less-watch-compiler#32]
if you check http://lesscss.org/#getting-started

```
var less = require('less');

less.render('.class { width: (1 + 1) }',
    {
      paths: ['.', './lib'],  // Specify search paths for @import directives
      filename: 'style.less', // Specify a filename, for better error messages
    },
    function (e, output) {
       console.log(output.css);
    });

```
there is missing config - if you got app.less which has dependency lets say layout.less [which is located not in same dir] and you do @import ".../layout" inside app.less, it will do not work, as it do have this path included, to make it work you need todo a lot of ../../ stuff to navigate to the right file, but if you would have an option to include directories which need to scan for includes, then all should work without many "../.. ":)

**Comment by jonycheung** [comment]
@eugene-matvejev could you let me know the version you are using? Are you using the latest?

If possible, would love a branch with the test case you mentioned (using the files in the "tests" folder

**Comment by jonycheung** [comment]
is this the same as #30 ?

**Comment by jonycheung** [comment]
PR

**Comment by eugene-matvejev** [comment]
thanks! I'll check it :)
