### ISSUE TITLE
Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by serjp** [jonycheung/deadsimple-less-watch-compiler#35]
Defects:
- [x] Did you run `npm install` and `npm update`
- [ ] Did you pull the latest code from `master` branch?

Steps to reproduce:
# Create a new file in the <source_dir>
#
#

Actual Results:
```
fs.js:681
 return binding.read(fd, buffer, offset, length, position);
                ^

Error: EISDIR: illegal operation on a directory, read
   at Object.fs.readSync (fs.js:681:18)
   at tryReadSync (fs.js:542:20)
   at Object.fs.readFileSync (fs.js:585:19)
   at Object.findLessImportsInFile (C:\Users\Sergio\AppData\Roaming\npm\node_modules\less-watch-compiler\lib\filesearch.js:11:40)
   at C:\Users\Sergio\AppData\Roaming\npm\node_modules\less-watch-compiler\lib\lessWatchCompilerUtils.js:106:62
   at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @1.0.0 watch-css: `less-watch-compiler src/less public/css style.less --source-map`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @1.0.0 watch-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sergio\AppData\Roaming\npm-cache\_logs\2017-08-14T14_09_33_358Z-debug.log
npm run watch-css exited with code 1
```

Expected Results:
- No errors

**Comment by jonycheung** [comment]
@serjp which version of `less-watch-compiler` Could you try the latest?

**Comment by serjp** [comment]
@jonycheung `less-watch-compiler@1.6.7`, the latest in npm. Tried version 1.6.13 - seems to be ok.

**Comment by mickeyvip** [comment]
I am experiencing the same problem with every version > `1.4` (`1.4.2` works ok).

Just set the `watchFolder` to be relative: 

`./less` 
`../src/less` (in my case)

and the exception is thrown.

Debugging the code of the latest version (`1.10`) I encountered the following code in `lessWatchCompilerUtils.js:184`:

```javascript
fileWatcher: function fileWatcher(f, files, options, filelist, fileimportlist, watchCallback) {
  if (filelist.indexOf(f) !== -1) return;
  filelist[filelist.length] = f;

  if (f.indexOf('.') !== -1) {
    fileimportlist[f] = fileSearch.findLessImportsInFile(f);
  }
  lessWatchCompilerUtilsModule.setupWatcher(f, files, options, watchCallback);
  for (var i in fileimportlist[f]) {
    if (filelist.indexOf(fileimportlist[f][i]) === -1) {
      lessWatchCompilerUtilsModule.setupWatcher(path.normalize(path.dirname(f) + '/' + fileimportlist[f][i]), files, options, watchCallback);
    }
  }
}
```

this function is called (probably the first time) with `f` set to the `watchFolder` and the second `if` (`if (f.indexOf('.') !== -1)`) will resolve to `true` if `f` has `.` inside it (and every relative folder name does) calling `fileSearch.findLessImportsInFile(f)` which will fail by calling `fs.readFileSync(f, 'utf8')` in `filesearch.js:15`.

The condition `if (f.indexOf('.') !== -1)` if pretty fragile one. Why not checking if `f` is a directory?

Changing the condition to `if (f.lastIndexOf('.') > 2)` solves the problem for me, but it's a hack.

Thank you.
