### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by serjp** [jonycheung/deadsimple-less-watch-compiler#36]
Defects:
- [ ] Did you pull the latest code from `master` branch?
- [ ] Did you run `npm install` and `npm update`

Steps to reproduce:
# Rename file in the <source_dir>, even when this file is not imported in the main less file
#
#

Actual Results:
```
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Sergio\Documents\projects\starwind-resource-library\src\less\base.less'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.findLessImportsInFile (C:\Users\Sergio\AppData\Roaming\npm\node_modules\less-watch-compiler\lib\filesearch.js:11:40)
    at StatWatcher.<anonymous> (C:\Users\Sergio\AppData\Roaming\npm\node_modules\less-watch-compiler\lib\lessWatchCompilerUtils.js:95:54)
    at emitTwo (events.js:125:13)
    at StatWatcher.emit (events.js:213:7)
    at StatWatcher._handle.onchange (fs.js:1452:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @1.0.0 watch-css: `less-watch-compiler src/less public/css style.less --source-map`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @1.0.0 watch-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sergio\AppData\Roaming\npm-cache\_logs\2017-08-14T14_34_17_645Z-debug.log
```

Expected Results:
- No errors

**Comment by serjp** [comment]
Don't see this error in version 1.6.13. However there is another bug with renaming. When rename the file more than once watcher does'nt watch it anymore.

**Comment by Kequc** [comment]
I performed a npm update recently and have started seeing the error reported in the OP.

`less-watch-compiler ./less ./public/stylesheets style.less`

Where my `./less` directory contains a `style.less` file. I receive ENOENT regardless of whether there is already compiled output in the destination directory.

**Comment by Kequc** [comment]
Confirmed downgrading to `1.4.2` removes the error. Not the earliest version that works, just that at least `1.7.0` seems to be broken for me.

**Comment by jonycheung** [comment]
@serjp / @Kequc Could you please try `v1.10.2` and see if this issue is fixed? If so, please close

**Comment by jonycheung** [comment]
Please reopen if this is still an issue.
