### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [jonycheung/deadsimple-less-watch-compiler#37]
$ npm --version
5.3.0

ran install and update and still didn't work

$ npm install -g less-watch-compiler
npm ERR! path /usr/local/lib/node_modules/less-watch-compiler/dist/less-watch-compiler.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/less-watch-compiler/dist/less-watch-compiler.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/williamrusnack/.npm/_logs/2017-08-15T11_52_04_687Z-debug.log

**Comment by jonycheung** [comment]
I'm on it..

**Comment by jonycheung** [comment]
@BebeSparkelSparkel  This is fixed now in v1.6.13 - `npm i -g less-watch-compiler@1.6.13`

**Comment by BebeSparkelSparkel** [comment]
Thanks!
