### ISSUE TITLE
Using with create react app

### ISSUE THREAD

**Issue by Martinsos** [jonycheung/deadsimple-less-watch-compiler#40]
Hi,
I am looking to use this package with create-react-app generated application, since this package is a good way to do it without ejecting the config files (which makes whole process more complicated).

However, the features that I need for that are:
- ability to run less watch compiler only once when needed, without the actual watching, since this enables me to use the same tool when building (autoless has this).
- ability for watcher to recursively go through the given src directory, compile files and reproduce that structure in the given dst directory. Hmm this is probably tricky because it may compile again files that were already imported in some other file? I guess there could be an option to compile only those that are not imported by the others.

I know I am asking for a lot here, but I was wondering how hard is this to do? From what I read, this is not supported yet, correct?

Since ant design is growing very popular and it is using less, and this plugin enables create-react-app users to add less support without ejecting, this features would make it ideal for that and therefore probably used a lot.

Thanks!

**Comment by jonycheung** [comment]
@Martinsos 
- The first point could be easy (`--runonce`). I'll start looking into that.
- The second one is one that I want to fix for a while but haven't gotten around as it's a bit tricky.

**Comment by Martinsos** [comment]
@jonycheung thanks for quick answer!
You mean tricky because it is not really clear how it should work? If it is too complicated to define in a nice way, maybe it is not a feature that should be implemented hm. I guess one simple way would be to just have it compile each file in the directory structure as if it was a main file. That would work for my use case -> maybe it would generate few redundant files but it would not be a problem I think. Maybe this is too specific?

**Comment by jonycheung** [comment]
Currently it work almost like you described. It renders all the the file in root of the target folder. It's smart to skip rendering of imported files.

**Comment by Martinsos** [comment]
Oh, so right now it will compile all of the files from the source tree but then put them all into the root of target folder? In my case, I just want them created next to the less files. But to be honest, what I am asking does maybe sound too specific.

**Comment by jonycheung** [comment]
@Martinsos #26 asks for the same thing and I'm wondering what the use case is because mixing `src` and `dest` files in one folder seems messy to me. Could you tell me a little more?

**Comment by Martinsos** [comment]
Alright, yes, that is the same use case it seems.
The thing is, create-react-app webpack setup allows you to bind each css file with corresponding js file by having `import './foo.css'.` in a js file. Because of that, you end up writing css files throughout the code tree next to corresponding .js files.

Next thing is that create-react-app hides webpack and other build setup from you. If you want to change webpack configuration or do some more serious changes to build process, you have to run `eject` command which spills all the configs and then you have to manage the build process manually from that moment.

If you wanted to use less properly in your project that was created with `create-react-app`, you would in general have to do an `eject` to configure the build process to support it. However, there is also an approach that does not need `eject`and it is described on `create-react-app` page: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc, and it needs the features that I described above.

**Comment by rogierslag** [comment]
The tool still does not travel through the source recursively?

**Comment by speedingdeer** [comment]
Same here :(
