### ISSUE TITLE
--run-once

### ISSUE THREAD

**Issue by eugene-matvejev** [jonycheung/deadsimple-less-watch-compiler#50]
less-watch-compiler - 1.10.0
node - 6.11.2 and 8.9.3

Steps to reproduce: [with example repo]
* git clone git@github.com:eugene-matvejev/battleship-game-gui-react-js.git
* cd battleship-game-gui-react-js; npm i;
* https://github.com/eugene-matvejev/battleship-game-gui-react-js/pull/186
* npm run generate:css

Actual Results:
- no files created in src/stylesheets/css

Expected Results:
- should create css files in src/stylesheets/css

P.S. if don't use such option and run in watch, and execute and then change file -> it save a output :)

**Comment by eugene-matvejev** [comment]
bump! works on node 8.9.3

**Comment by jonycheung** [comment]
Thanks for the issue and reproduction steps. I'll take a look at this probably after the holidays.

**Comment by jonycheung** [comment]
@eugene-matvejev the latest version `1.11.x` should fix this.
