### ISSUE TITLE
Recompile imported LESS files when changed

### ISSUE THREAD

**Issue by JamesMcIntosh** [jonycheung/deadsimple-less-watch-compiler#55]
* Reference import
```@import (reference) "theme.less"```
These are not recognised by the regex in filesearch.js

* Relative and absolute imports
```@import "../theme.less"```
```@import "/theme.less"```
If you reference a LESS using relative or absolute path

* Excluding the .less extension when referring to files
``````@import "theme"```
This is recognised by the compiler but the comparison in less-watch-compiler.js line 119 does not work
http://lesscss.org/features/#import-directives-feature

Actual Results:
- None of these cases work

Expected Results:
- The should work

**Comment by JamesMcIntosh** [comment]
This fix does not handle when there are transient dependencies of import statements.

i.e. _homepage.less_ which imports _theme.less_ which imports _colors.less_

Changing _colors.less_ will not cause _homepage.less_ to regenerate, it should.

**Comment by jonycheung** [comment]
Closing this one as we have a new issue to track transitive dependencies.
