### ISSUE TITLE
concat and minify result files

### ISSUE THREAD

**Issue by vit134** [jonycheung/deadsimple-less-watch-compiler#56]
hi i have a little problem

I have some .less files in my app, when i run build-css ("build-css": "less-watch-compiler --v --run-once src/components/ src/styles/") I get the same directory structure as the original with separate .css files. How to merge all the .less files into one and not create many different .css files?

**Comment by jonycheung** [comment]
@vit134 could you try to pass in a less plugin to concat or minify.
Make sure also your included files have '_' in front of it. OR specify a main file (see readme)

Please also try to make sure you are on 1.11.x

**Comment by jonycheung** [comment]
Please open if you have further questions
