### ISSUE TITLE
Cannot find module './src/common'

### ISSUE THREAD

**Issue by alana-farkas-zocdoc** [jonycheung/deadsimple-less-watch-compiler#57]
Hello,

When running the less-watch-compiler <source_dir> <destination_dir> command, I get thrown an error immediately. I updated to the latest version (I think?) by running ` npm update less-watch-compiler `. There was no output in the terminal after running that command. Trying to check the version gives me the same error. I've never seen this error before and don't know what to do! Any suggestions? Thank you. 

![screen shot 2018-02-07 at 5 07 07 pm](https://user-images.githubusercontent.com/31899543/35944415-4d4134b8-0c2a-11e8-8090-0e7131f310b0.png)

**Comment by jonycheung** [comment]
When you just run the command, it should give you 

`
Missing arguments. Example:
	node less-watch-compiler.js FOLDER_TO_WATCH FOLDER_TO_OUTPUT
	Example 1: To watch all files under the folder "less" and compile all into a folder "css".
		 less-watch-compiler less css
`

**Comment by jonycheung** [comment]
Please re-open if you have any further questions.
