### ISSUE TITLE
Windows 7 - after compiling creates undeleteable folder with ".."

### ISSUE THREAD

**Issue by Etrimon** [jonycheung/deadsimple-less-watch-compiler#58]
Are you using the command line tool `less-watch-compiler`? Yes
If you are using the command line tool, which version are you using (`less-watch-compiler --version` to find out)? 1.10.2
Is the issue reproducible after updating to the latest version (` npm update less-watch-compiler`)? Yes

Steps to reproduce:
- 1. Created config file 
 {
    "watchFolder" : "../less",
    "outputFolder" : "../css",
    "mainFile" : "styles.less",
    "minified" : false
 }
- 2. folder and files structure:
 /css/styles.css
 /incl/less.config.json
 /less/styles.less (+ other in styles.less included less files)
 
- 3. run less-watch-compiler --config less.config.json

Actual Results:
- After the less file was changed and scripts run, it creates a new folder "css.." inside the project. This folder is undeletedable.

**Comment by jonycheung** [comment]
could you update to `1.11.0` and see if this is still an issue?

**Comment by jonycheung** [comment]
Please re-open if you have any questions or issues after testing.
