### ISSUE TITLE
Compiler creating css in wrong directory

### ISSUE THREAD

**Issue by altwohill** [jonycheung/deadsimple-less-watch-compiler#60]
Are you using the command line tool `less-watch-compiler`?  **Yes**
If you are using the command line tool, which version are you using (`less-watch-compiler --version` to find out)? **1.11.0**
Is the issue reproducible after updating to the latest version (` npm update less-watch-compiler`)? **Yes**

Steps to reproduce:

1. Upgrade from 1.8.0 to 1.11.0
1. Watch LESS, with npm: `"less-watch-compiler src/less public/css"`
1. Edit any file

Actual Results:
- Output is created in the wrong directory. It appears to be concatenating the arguments weirdly. 

> The file: src\less\index.less was changed. Recompiling public/csssrc\less/index.css at 19:28:34 on 06/03/2018

Expected Results:
- Output to be created in `public/css/index.css`

Note:
This is on Windows

**Comment by jonycheung** [comment]
Looks like a bug, I'll look at this soon.

**Comment by mobiusnz** [comment]
Cool. Downgrading back to 1.8.0 works around the problem

**Comment by filecage** [comment]
Ran into the same issue, my call of `less-watch-compiler src-client/style build/assets style.less` compiles changes from imported styles to `build/assetssrc-client\style/style.css`.

However, any changes inside my entry point `style.less` are handled correctly.

**Comment by asiby** [comment]
This is not a bug. Windows does not use the "/" character as directory separator.

I am using a `less-watch-compiler.config.json` configuration file and the following worked for me ...

```json
{
  "watchFolder": "site\\css",
  "outputFolder": "site\\css"
}
```

**Comment by mobiusnz** [comment]
> Windows does not use the "/" character as directory separator. 

This is not true.  The DOS command line originally would not accept "/" as it used it for switches, however DOS (and Windows) has always accepted "/" as a directory separator.

![image](https://user-images.githubusercontent.com/629254/38842901-b15ce9a0-4240-11e8-8285-9483222af860.png)

**Comment by jonycheung** [comment]
Hi everyone, could you see if `1.11.2` fixes this issue.

**Comment by altwohill** [comment]
Still getting the issue in 1.11.2

> The file: src\less\index.less was changed. Recompiling public/csssrc\less/index.css at 08:07:10 on 08/05/2018

**Comment by filecage** [comment]
Works for me:
```
$ C:\develop\foobar>node_modules\.bin\less-watch-compiler --version
1.11.2

$ less-watch-compiler src-client/style build/assets style.less
Watching directory for file changes.
The file: src-client\style\MainContainer.less was changed. Recompiling build/assets/style.css at 11:09:26 on 09/05/2018
```
while:
```
$ C:\develop\misc\foobar>node_modules\.bin\less-watch-compiler --version
1.11.0

$ less-watch-compiler src-client/style build/assets style.less
Watching directory for file changes.
The file: src-client\style\style.less was changed because src-client\style\MainContainer.less is specified as an import.  Recompiling build/assetssrc-client\style/style.css at 11:14:14 on 09/05/2018
```

@altwohill does the issue appear only when changing imported files or *any* files?

**Comment by hatton** [comment]
Using Windows, 1.11.3

Steps to reproduce:
1. Create this file tree:

```
└───some
    └───styles
            styles.less
```

2. ``yarn less-watch-compiler some/less some/css``

Actual Results:

```
└───some
    ├───csssome  <--- this is the error
    │   └───styles
    │           styles.css
    │
    └───less
            styles.less
```

``yarn less-watch-compiler some\less some\css`` fails entirely.

``yarn less-watch-compiler some\\less some\\css`` works fine. However, this is going in a packages.json script that is used on multiple platforms, hence the importance of supporting forward slashes.
