### ISSUE TITLE
Initial launch uses a different directory as watcher

### ISSUE THREAD

**Issue by zhaoyi0113** [jonycheung/deadsimple-less-watch-compiler#61]
I am using this command:
```
node_modules/.bin/less-watch-compiler src/assets/less/  ./   qbo.less 
```

it generates the `qbo.less` at the root directory of my project. When a file is changed, the watcher generates the file under `src/assets/less` directory. It looks like they are using different path algorithm.

**Comment by jonycheung** [comment]
Will look into this.

**Comment by jonycheung** [comment]
@zhaoyi0113 Deployed the fix to npm. Let me know if this is ok.
