### ISSUE TITLE
less-watch-compiler returns error code 0 for less compilation errors

### ISSUE THREAD

**Issue by smifun** [jonycheung/deadsimple-less-watch-compiler#62]
Are you using the command line tool `less-watch-compiler`?
If you are using the command line tool, which version are you using (`less-watch-compiler --version` to find out)?
`1.11.0`
Is the issue reproducible after updating to the latest version (` npm update less-watch-compiler`)?
`yes`

### In watch mode it make sense to just log error but in run-once process should exit with error code so that calling process could handle failure. Ex in CI env.

Steps to reproduce:
- mkdir -p example && echo error > example/example.less
- `less-watch-compiler example example --run-once`

Actual Results:
- less-watch-compiler logs error and exists with code 0 (success)

Expected Results:
- less-watch-compiler logs error and exits with code 1(non zero)

**Comment by smifun** [comment]
I prepared fix.

**Comment by jonycheung** [comment]
@smifun Thanks. Do you mind a PR?

**Comment by smifun** [comment]
#63

**Comment by jonycheung** [comment]
Deployed the fix to npm. Let me know if this is ok.
