### ISSUE TITLE
Nested dependency on `hoek` package raises security vulnerability

### ISSUE THREAD

**Issue by ironng** [jonycheung/deadsimple-less-watch-compiler#66]
Github has flagged versions of [hoek](https://github.com/hapijs/hoek) older than 5.0.3 and 4.2.1 as having security vulnerabilities. (See https://github.com/hapijs/hoek/issues/247.) The `less` version required by the current version of this package (1.11.2) still contains this as a nested dependency.  If `less` is updated to the latest version (3.0.4), this vulnerability warning can be avoided.

**Comment by jonycheung** [comment]
@ironng  Updated the dep, please let me know if you need anything else.

**Comment by ironng** [comment]
@jonycheung Great, thank you!
