### ISSUE TITLE
Current version of less breaks media query aspect ratios

### ISSUE THREAD

**Issue by JamesMcIntosh** [jonycheung/deadsimple-less-watch-compiler#69]
Version 3.0.4 of less is not yet a very good and stable release.

They have broken things like aspect ratios, see:
https://github.com/less/less.js/issues/1880

Having a media query like the following breaks because it is "16/9" is converted to a decimal 1.7777778
```@media (max-width: 50em) and (max-aspect-ratio: 16/9) ```

**Comment by jonycheung** [comment]
Just released an update @1.11.7 with `less 3.8.1`. Hope this solves the problem.

**Comment by JamesMcIntosh** [comment]
Awesome, I'll give it a test!

**Comment by JamesMcIntosh** [comment]
This LESS version does fix the problem but it requires a command line option to enable the functionality, see the math section http://lesscss.org/usage/#less-options

Looks like updating the `lessWatchCompilerUtils.js` compileCSS function adding 
```
var math = lessWatchCompilerUtilsModule.config.math ? ' --math=' + lessWatchCompilerUtilsModule.config.math  : '';
...
var command = 'lessc' + math + sourceMap + enableJsFlag + minifiedFlag + plugins + ' ' + JSON.stringify(file) + ' ' + outputFilePath;
```

and adding the option to `less-watch-compiler.js` init() function
```
if (program.math) lessWatchCompilerUtils.config.math = program.math;
```

Should be enough to activate the functionality, I'll look at a PR.

**Comment by JamesMcIntosh** [comment]
PR #77 adds the functionality and improves the setup of the unit tests to stop configuration accidently spilling over between tests.

**Comment by jonycheung** [comment]
You can now pass less options in `1.13.0` using --less-args
