### ISSUE TITLE
Package relies on config.json to be present

### ISSUE THREAD

**Issue by danielkhan** [jonycheung/deadsimple-less-watch-compiler#7]
The documentation suggests that the config file ist optional but you are trying to access it without checking for existence.

There is a valid lookup for less-watch-compiler.config.json afterwards - I didn't do a pull request because I don't know what's the plan with the other config file name.

**Comment by izeta** [comment]
Yeah, I was trying to run less-watch-compiler and it was crashing trying to look for the files.
