### ISSUE TITLE
Watching directory for changes, but don't react on changes made

### ISSUE THREAD

**Issue by ElliottRod** [jonycheung/deadsimple-less-watch-compiler#9]
Hi,

I have install the less-wacher-compiler and it seems all right until I call the command to start watcher. Then it get stuck on "Watching directory for file changes.", and I make changes on my less-folder less-files, but nothing happens on terminail.

Any suggestions?

BR
Elliott

**Comment by badcrocodile** [comment]
I'm getting the same behavior as Elliott. I've tried absolute paths from '/' down as well paths relative to my config.json file without any luck. Screen output claims to be Watching directory for file changes but it's just not picking it up.

**Comment by jonycheung** [comment]
HI guys, I merged @badcrocodile 's changes into master. Let me know if that worked and feel free to close.
