### ISSUE TITLE
Remove unused dependency - opencollective ?

### ISSUE THREAD

**Issue by ksathyanm** [jonycheung/deadsimple-less-watch-compiler#95]
Are you using the command line tool `less-watch-compiler`?
Yes

If you are using the command line tool, which version are you using (`less-watch-compiler --version` to find out)?
1.14.1

Is the issue reproducible after updating to the latest version (` npm update less-watch-compiler`)?
Yes

Steps to reproduce:

-  ~~`npm install`  on the project directory~~
-  `rm -rf ./node_modules/ && npm install`  on the project directory

Actual Results:

- `npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`

Expected Results:

-  No deprecation warnings

Here is the `npm ls core-js` result. Also, figured out that https://github.com/jonycheung/deadsimple-less-watch-compiler/pull/79 added `opencollective` dependency which is really not used anywhere or needed.
```
$ npm ls core-js
+-- less-watch-compiler@1.14.1
| `-- opencollective@1.0.3
|   `-- babel-polyfill@6.23.0
|     +-- babel-runtime@6.26.0
|     | `-- core-js@2.6.11
|     `-- core-js@2.6.11
```

**Comment by ksathyanm** [comment]
@jonycheung - ping

**Comment by jonycheung** [comment]
@ksathyanm Thanks for the ping. Which version of node and npm are you on?

**Comment by jonycheung** [comment]
I'm not seeing this error. Just wanted to make sure I'm fixing the right thing.

**Comment by ksathyanm** [comment]
@jonycheung Here are the versions of node and npm.

```
$ node -v
v12.14.0
$ npm -v
6.13.4
```
I see the warning only on npm clean installation.

```
$ rm -rf ./node_modules/ && rm package-lock.json && npm install
```

**Comment by GuillaumeLachaud** [comment]
My build is now failing with the following. Same code was building fine this morning so I guess this commit and the subsequent publish is the culprit.

` warning "workspace-aggregator-106f1d29-f841-45dc-9f47-9f04317fc9e5 > junon > style-loader@1.1.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
       [4/4] Building fresh packages...
       error /tmp/build_17bf171fa0ba92efd6443d35681cdde5/node_modules/less-watch-compiler: Command failed.
       Exit code: 127
       Command: opencollective-postinstall
       Arguments: 
       Directory: /tmp/build_17bf171fa0ba92efd6443d35681cdde5/node_modules/less-watch-compiler
       Output:
       /bin/sh: 1: opencollective-postinstall: not found`

**Comment by ksathyanm** [comment]
@jonycheung `opencollective-postinstall` and `shelljs` needs to be part of `dependencies`.

@GuillaumeLachaud

**Comment by ksathyanm** [comment]
@monkeywithacupcake `opencollective` was added to `dependencies` as part of #79. Can you please confirm if it is really needed?

**Comment by stell** [comment]
Same error here:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! less-watch-compiler@1.14.4 postinstall: `opencollective-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the less-watch-compiler@1.14.4 postinstall script.

**Comment by jonycheung** [comment]
just reverted the change and published 1.14.5

**Comment by jonycheung** [comment]
1.14.6 is released with this PR. Please let me know if there's any issue. Sorry about the earlier covfefe,

**Comment by cap10morgan** [comment]
I'm seeing this error again upgrading to 1.16.2 from 1.14.6 on node 14.17.3 installed via Homebrew on macOS. I.e. `sh: opencollective-postinstall: command not found`

**Comment by monkeywithacupcake** [comment]
The `opencollective-postinstall` can be completely removed from the package. it is no longer necessary
